version: "3.3"
services:
  httpbin:
    image: httpbin:latest
    build:
      context: .
      dockerfile: ./Dockerfile
  httpbin-alpine:
    image: httpbin:alpine
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
  httpbin-nginx:
    image: httpbin:nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
  httpbin-unit:
    image: httpbin:unit
    build:
      context: .
      dockerfile: ./Dockerfile.unit
  httpbin-bullseye-httpd:
    image: httpbin:bullseye-httpd
    build:
      context: .
      dockerfile: ./Dockerfile.bullseye-httpd
  httpbin-alpine-httpd:
    image: httpbin:alpine-httpd
    build:
      context: .
      dockerfile: ./Dockerfile.alpine-httpd
